<?php
echo "<!DOCTYPE html>\n";
echo "html lang=\"zh-CN\">\n";
echo " <head>\n";
echo " <meta charset=\"UTF-8\" />\n";
echo " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n";
echo " <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\n";
echo " <title>服务器地址列表</title>\n";
echo "!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓表↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓格↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->\n";
echo " <link rel=\"stylesheet\" href=\"css/wdtab.css\">\n";
echo "!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->\n";
echo " <!--script type=\"text/javascript\" src=\"http://libs.baidu.com/jquery/1.7.2/jquery.js\"--><!--/script-->\n";
echo " <!--script type=\"text/javascript\" src=\"http://libs.baidu.com/jquery/1.7.2/jquery.min.js\"--><!--/script-->\n";
echo "!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓复制外观↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->\n";
echo " <script src=\"copy/jquery.min.js\"></script>\n";
echo "!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->\n";
echo " <!--link rel=\"stylesheet\" href=\"copy/prettify.css\"-->\n";
echo " <script src=\"copy/prettify.js\"></script>\n";
echo "!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓复制按键↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->\n";
echo " <script type=\"text/javascript\" src=\"js/wdcopy.js\"></script>\n";
echo " <link rel=\"stylesheet\" href=\"css/01.css\">\n";
echo "!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->\n";
echo "!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓站点图标↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->\n";
echo " <link rel=\"icon\" href=\"imgs/ktwd.png\"/>\n";
echo "!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->\n";
echo "!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓背↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓景↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->\n";
echo "<!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑背↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑景↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->\n";
echo " <style>\n";
echo " * {\n";
echo "   margin: 0;\n";
echo "   padding: 0;\n";
echo "   text-underline: none;\n";
echo "   text-decoration: none;\n";
echo "   font-family: \"Microsoft YaHei\", sans-serif;\n";
echo "   -webkit-tap-highlight-color: transparent;\n";
echo "   -webkit-font-smoothing: antialiased;\n";
echo " }\n";
echo " html, body, #app {\n";
echo "   position: relative;\n";
echo "   padding: 0;\n";
echo "   margin: 0;\n";
echo "   width: 100%;\n";
echo "   height: 100%;\n";
echo "   color: #333333;\n";
echo " }\n";
echo " #app {\n";
echo "   padding: 60px;\n";
echo "   overflow: auto;\n";
echo "   box-sizing: border-box;\n";
echo "   background-repeat: no-repeat; /* 背景图片不重复 */\n";
echo "   background-image: url(imgs/bj1.jpg);/* 背景图片覆盖整个容器 */\n";
echo "   opacity: 1.5; /* 背景图片透明度 */\n";
echo " }\n";
echo " #app::-webkit-scrollbar { width: 0 !important;}\n";
echo " .title {\n";
echo "   padding: 0 0 60px;\n";
echo "   width: 100%;\n";
echo "   color: white;\n";
echo "   font-size: 50px;\n";
echo "   font-weight: 800;\n";
echo "   text-align: center;\n";
echo "   text-shadow: 5px 2px 10px #0000009c;\n";
echo " }\n";
echo " .sum {\n";
echo "   position: fixed;\n";
echo "   bottom: 0;\n";
echo "   right: 0;\n";
echo "   padding: 6px 20px;\n";
echo "   color: white;\n";
echo "   font-weight: bold;\n";
echo "   border-radius: 4px;\n";
echo "   border-bottom-right-radius: 0;\n";
echo "   border: 1px solid transparent;\n";
echo "   background: rgba(0, 0, 0, 0.6);\n";
echo "   z-index: 4;\n";
echo " }\n";
echo " a {\n";
echo "   position: relative;\n";
echo "   display: inline-block;\n";
echo "   top: 0;\n";
echo "   padding-bottom: 10px;\n";
echo "   width: 310px;\n";
echo "   height: 330px;\n";
echo "   color: white;\n";
echo "   overflow: hidden;\n";
echo "   border: 1px solid #4E84E6;\n";
echo "   border-radius: 4px;\n";
echo "   text-decoration: none;\n";
echo "   background-color: #4E84E6;\n";
echo "   transition: 0.3s all;\n";
echo " }\n";
echo " .img {\n";
echo "   width: 100%;\n";
echo "   height: 180px;\n";
echo "   background-size: cover;\n";
echo "   -webkit-background-size: cover;\n";
echo " }\n";
echo " .name, .intro, .tips {\n";
echo "   position: absolute;\n";
echo "   left: 20px;\n";
echo "   width: calc(330px - 53px);\n";
echo "   transition: 0.5s all;\n";
echo " }\n";
echo " .name {\n";
echo "   top: 190px;\n";
echo "   font-size: 20px;\n";
echo "   font-weight: bolder;\n";
echo " }\n";
echo " .name i {\n";
echo "   position: relative;\n";
echo "   top: -3px;\n";
echo "   display: inline-block;\n";
echo "   margin-left: 10px;\n";
echo "   font-size: 12px;\n";
echo "   padding: 2px 6px;\n";
echo "   border-radius: 4px;\n";
echo "   color: white;\n";
echo "   background-color: #56B962;\n";
echo " }\n";
echo " .intro {\n";
echo "   top: 226px;\n";
echo "   height: 110px;\n";
echo "   font-size: 14px;\n";
echo " }\n";
echo " .star {\n";
echo "   position: absolute;\n";
echo "   left: 20px;\n";
echo "   bottom: 10px;\n";
echo "   transition: 0.5s all;\n";
echo " }\n";
echo " .tips {\n";
echo "   bottom: 0;\n";
echo "   left: 100%;\n";
echo "   width: 312px;\n";
echo "   height: 150px;\n";
echo "   color: white;\n";
echo "   font-size: 30px;\n";
echo "   font-weight: bold;\n";
echo "   text-align: center;\n";
echo "   line-height: 150px;\n";
echo " }\n";
echo " .tips img {\n";
echo "   display: inline-block;\n";
echo "   margin-right: 6px;\n";
echo "   height: 36px;\n";
echo "   vertical-align: sub;\n";
echo " }\n";
echo " section {\n";
echo "   display: grid;\n";
echo "   justify-content: space-evenly;\n";
echo "   justify-items: center;\n";
echo "   grid-row-gap: 50px;\n";
echo "   grid-template-columns: repeat(auto-fill, 320px);\n";
echo " }\n";
echo " section a:hover {\n";
echo "   top: -10px;\n";
echo "   color: #333333;\n";
echo "   border: 1px solid transparent;\n";
echo "   background: rgba(0, 0, 0, 0.6);\n";
echo "   box-shadow: 2px 11px 20px 0 rgba(0, 0, 0, 0.6);\n";
echo " }\n";
echo " section a:hover .name, section a:hover .intro, section a:hover .star {\n";
echo "   left: -100%;\n";
echo " }\n";
echo " section a:hover .tips {\n";
echo "   left: 0;\n";
echo " }\n";
echo " .back {\n";
echo "   display: block;\n";
echo "   position: fixed;\n";
echo "   top: 30px;\n";
echo "   left: 30px;\n";
echo "   padding: 0;\n";
echo "   margin: 0;\n";
echo "   width: 80px;\n";
echo "   height: 80px;\n";
echo "   border-radius: 50%;\n";
echo "   border: none;\n";
echo "   cursor: pointer;\n";
echo "   z-index: 3;\n";
echo "   -webkit-background-size: 60px 60px;\n";
echo "   transition: 0.3s all;\n";
echo "   background-size: 60px 60px;\n";
echo "   background-repeat: no-repeat;\n";
echo "   background-position: center center;\n";
echo "   background-image: url(http://upyun.luckly-mjw.cn/Assets/blog/click.png);\n";
echo "   background-color: rgba(0, 0, 0, 0.5);\n";
echo " }\n";
echo " .back:hover {\n";
echo "   background-color: rgba(0, 0, 0, 0.8);\n";
echo " }\n";
echo " </style>\n";
echo "/head>\n";
echo "!--h1 style=\"color:blue;\">这是一个蓝色的标题</h1-->\n";
echo "!--p style=\"color:red;\">这是一段红色的文本</p-->\n";
echo "body>\n";
echo "div id=\"app\">\n";
echo " <a class=\"back\" title=\"返回上级\" href=\"index.html\"></a>\n";
echo " <div class=\"title\">海外宽带直连服务器地址列表</div>\n";
echo "<!--尺寸</font>-->\n";
echo "<table id=\"menuTable\">\n";
echo "<tr style=\"display: table-rowspan; \">\n";
echo "<tr>\n";
echo "    <td><div style=\"text-align: center;\"><font size=5><p style=\"color:#ffe100;\">&nbsp;&nbsp;&nbsp;&nbsp;省&nbsp;&nbsp;&nbsp;&nbsp;</p></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><font size=5><p style=\"color:#ffe100;\">&nbsp;&nbsp;&nbsp;&nbsp;市&nbsp;&nbsp;&nbsp;&nbsp;</p></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><font size=5><p style=\"color:#ffe100;\">服务器地址</p></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><font size=5><p style=\"color:#ffe100;\">用户名1</p></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><font size=5><p style=\"color:#ffe100;\">用户名2</p></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><font size=5><p style=\"color:#ffe100;\">&nbsp;&nbsp;密&nbsp;&nbsp;码&nbsp;&nbsp;</p></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><font size=5><p style=\"color:#ffe100;\">&nbsp;&nbsp;状&nbsp;&nbsp;态&nbsp;&nbsp;</p></font></div></td>\n";
echo "   </tr>\n";
echo "  <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">直辖市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">北京市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzbeijing.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">beijing1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "  </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">直辖市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">上海市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzshanghai.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">shanghai1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">直辖市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">天津市</h2></div></td>\n";
echo " <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">haiwai.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#EC4C40;\">暂未部署</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">直辖市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">重庆市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzchongqing.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">chongqing1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">广东省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">广州市</h2></div></td>\n";
echo " <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzguangzhou.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">guangzhou1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">广东省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">深圳市</h2></div></td>\n";
echo " <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzshenzhen.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">shenzhen1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽10M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">广东省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">中山市</h2></div></td>\n";
echo " <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzzhongshan.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zhongshan1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽10M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">江苏省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">苏州市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzsuzhou.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">suzhou1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">江苏省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">镇江市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzzhenjiang.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zhenjiang1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽10M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">贵州省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">贵阳市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzguiyang.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">guiyang1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">四川省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">成都市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzchengdu.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">chengdu1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">四川省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">德阳市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzdeyang.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">deyang1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽10M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">陕西省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">西安市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzxian.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">xian1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">湖南省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">长沙市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzchangsha.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">changsha1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽20M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">湖北省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">武汉市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzwuhan.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wuhan1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽15M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">河南省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">新乡市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzxinxiang.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">xinxiang1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽10M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">浙江省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">杭州市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzhangzhou.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">hangzhou1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">/</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽15M</h2></div></td>\n";
echo "    </tr>\n";
echo "    <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">浙江省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">绍兴市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzhaoxing.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">shaoxing1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">/</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽15M</h2></div></td>\n";
echo "    </tr>\n";
echo "    <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">安徽省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">合肥市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzhefei.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">hefei1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽10M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">安徽省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">芜湖市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzwuhu.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wuhu1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽15M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">辽宁省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">大连市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzdalian.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">dalian1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽30M</h2></div></td>\n";
echo "   </tr>\n";
echo "   <tr>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">福建省</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#FF763E;\">福州市</h2></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">zzfuzhou.wendy-ip.com</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">fuzhou1-10</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wdvpn</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\" class=\"content\"><font size=5><pre><p style=\"color:#3498db\">wd123</p></pre></font></div></td>\n";
echo "    <td><div style=\"text-align: center;\"><h2 style=\"color:#0ACD76;\">正常，带宽10M</h2></div></td>\n";
echo "   </tr>\n";
echo "  </tbody>\n";
echo "script src=\"js/jquery.filtertable.min.js\"></script>\n";
echo "script src=\"js/filtertable.js\"></script>\n";
echo "/table>\n";
echo "/body>\n";
echo "/html>\n";
?>