document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("  <head>");
document.writeln("  <meta charset=\'UTF-8\' />");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\' />");
document.writeln("  <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\' />");
document.writeln("  <title>服务器地址列表</title>");
document.writeln("<!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓表↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓格↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->");
document.writeln("  <link rel=\'stylesheet\' href=\'css/wdtab.css\'>");
document.writeln("<!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->");
document.writeln("  <!--script type=\'text/javascript\' src=\'http://libs.baidu.com/jquery/1.7.2/jquery.js\'--><!--/script-->");
document.writeln("  <!--script type=\'text/javascript\' src=\'http://libs.baidu.com/jquery/1.7.2/jquery.min.js\'--><!--/script-->");
document.writeln("<!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓复制外观↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->");
document.writeln("  <script src=\'copy/jquery.min.js\'></script>");
document.writeln("<!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->");
document.writeln("  <!--link rel=\'stylesheet\' href=\'copy/prettify.css\'-->");
document.writeln("  <script src=\'copy/prettify.js\'></script>");
document.writeln("<!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓复制按键↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->");
document.writeln("  <script type=\'text/javascript\' src=\'js/wdcopy.js\'></script>");
document.writeln("  <link rel=\'stylesheet\' href=\'css/01.css\'>");
document.writeln("<!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->");
document.writeln("<!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓站点图标↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->");
document.writeln("  <link rel=\'icon\' href=\'imgs/ktwd.png\'/>");
document.writeln("<!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->");
document.writeln("<!--↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓背↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓景↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓-->");
document.writeln("");
document.writeln("<!--↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑背↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑景↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑-->");
document.writeln("  <style>");
document.writeln("  * {");
document.writeln("    margin: 0;");
document.writeln("    padding: 0;");
document.writeln("    text-underline: none;");
document.writeln("    text-decoration: none;");
document.writeln("    font-family: \'Microsoft YaHei\', sans-serif;");
document.writeln("    -webkit-tap-highlight-color: transparent;");
document.writeln("    -webkit-font-smoothing: antialiased;");
document.writeln("  }");
document.writeln("  html, body, #app {");
document.writeln("    position: relative;");
document.writeln("    padding: 0;");
document.writeln("    margin: 0;");
document.writeln("    width: 100%;");
document.writeln("    height: 100%;");
document.writeln("    color: #333333;");
document.writeln("  }");
document.writeln("  #app {");
document.writeln("    padding: 60px;");
document.writeln("    overflow: auto;");
document.writeln("    box-sizing: border-box;");
document.writeln("    background-repeat: no-repeat; /* 背景图片不重复 */");
document.writeln("    background-image: url(imgs/bj1.jpg);/* 背景图片覆盖整个容器 */");
document.writeln("    opacity: 1.5; /* 背景图片透明度 */");
document.writeln("  }");
document.writeln("  #app::-webkit-scrollbar { width: 0 !important;}");
document.writeln("  .title {");
document.writeln("    padding: 0 0 60px;");
document.writeln("    width: 100%;");
document.writeln("    color: white;");
document.writeln("    font-size: 50px;");
document.writeln("    font-weight: 800;");
document.writeln("    text-align: center;");
document.writeln("    text-shadow: 5px 2px 10px #0000009c;");
document.writeln("  }");
document.writeln("  .sum {");
document.writeln("    position: fixed;");
document.writeln("    bottom: 0;");
document.writeln("    right: 0;");
document.writeln("    padding: 6px 20px;");
document.writeln("    color: white;");
document.writeln("    font-weight: bold;");
document.writeln("    border-radius: 4px;");
document.writeln("    border-bottom-right-radius: 0;");
document.writeln("    border: 1px solid transparent;");
document.writeln("    background: rgba(0, 0, 0, 0.6);");
document.writeln("    z-index: 4;");
document.writeln("  }");
document.writeln("  a {");
document.writeln("    position: relative;");
document.writeln("    display: inline-block;");
document.writeln("    top: 0;");
document.writeln("    padding-bottom: 10px;");
document.writeln("    width: 310px;");
document.writeln("    height: 330px;");
document.writeln("    color: white;");
document.writeln("    overflow: hidden;");
document.writeln("    border: 1px solid #4E84E6;");
document.writeln("    border-radius: 4px;");
document.writeln("    text-decoration: none;");
document.writeln("    background-color: #4E84E6;");
document.writeln("    transition: 0.3s all;");
document.writeln("  }");
document.writeln("  .img {");
document.writeln("    width: 100%;");
document.writeln("    height: 180px;");
document.writeln("    background-size: cover;");
document.writeln("    -webkit-background-size: cover;");
document.writeln("  }");
document.writeln("  .name, .intro, .tips {");
document.writeln("    position: absolute;");
document.writeln("    left: 20px;");
document.writeln("    width: calc(330px - 53px);");
document.writeln("    transition: 0.5s all;");
document.writeln("  }");
document.writeln("  .name {");
document.writeln("    top: 190px;");
document.writeln("    font-size: 20px;");
document.writeln("    font-weight: bolder;");
document.writeln("  }");
document.writeln("  .name i {");
document.writeln("    position: relative;");
document.writeln("    top: -3px;");
document.writeln("    display: inline-block;");
document.writeln("    margin-left: 10px;");
document.writeln("    font-size: 12px;");
document.writeln("    padding: 2px 6px;");
document.writeln("    border-radius: 4px;");
document.writeln("    color: white;");
document.writeln("    background-color: #56B962;");
document.writeln("  }");
document.writeln("  .intro {");
document.writeln("    top: 226px;");
document.writeln("    height: 110px;");
document.writeln("    font-size: 14px;");
document.writeln("  }");
document.writeln("  .star {");
document.writeln("    position: absolute;");
document.writeln("    left: 20px;");
document.writeln("    bottom: 10px;");
document.writeln("    transition: 0.5s all;");
document.writeln("  }");
document.writeln("  .tips {");
document.writeln("    bottom: 0;");
document.writeln("    left: 100%;");
document.writeln("    width: 312px;");
document.writeln("    height: 150px;");
document.writeln("    color: white;");
document.writeln("    font-size: 30px;");
document.writeln("    font-weight: bold;");
document.writeln("    text-align: center;");
document.writeln("    line-height: 150px;");
document.writeln("  }");
document.writeln("  .tips img {");
document.writeln("    display: inline-block;");
document.writeln("    margin-right: 6px;");
document.writeln("    height: 36px;");
document.writeln("    vertical-align: sub;");
document.writeln("  }");
document.writeln("  section {");
document.writeln("    display: grid;");
document.writeln("    justify-content: space-evenly;");
document.writeln("    justify-items: center;");
document.writeln("    grid-row-gap: 50px;");
document.writeln("    grid-template-columns: repeat(auto-fill, 320px);");
document.writeln("  }");
document.writeln("  section a:hover {");
document.writeln("    top: -10px;");
document.writeln("    color: #333333;");
document.writeln("    border: 1px solid transparent;");
document.writeln("    background: rgba(0, 0, 0, 0.6);");
document.writeln("    box-shadow: 2px 11px 20px 0 rgba(0, 0, 0, 0.6);");
document.writeln("  }");
document.writeln("  section a:hover .name, section a:hover .intro, section a:hover .star {");
document.writeln("    left: -100%;");
document.writeln("  }");
document.writeln("  section a:hover .tips {");
document.writeln("    left: 0;");
document.writeln("  }");
document.writeln("  .back {");
document.writeln("    display: block;");
document.writeln("    position: fixed;");
document.writeln("    top: 30px;");
document.writeln("    left: 30px;");
document.writeln("    padding: 0;");
document.writeln("    margin: 0;");
document.writeln("    width: 80px;");
document.writeln("    height: 80px;");
document.writeln("    border-radius: 50%;");
document.writeln("    border: none;");
document.writeln("    cursor: pointer;");
document.writeln("    z-index: 3;");
document.writeln("    -webkit-background-size: 60px 60px;");
document.writeln("    transition: 0.3s all;");
document.writeln("    background-size: 60px 60px;");
document.writeln("    background-repeat: no-repeat;");
document.writeln("    background-position: center center;");
document.writeln("    background-image: url(http://upyun.luckly-mjw.cn/Assets/blog/click.png);");
document.writeln("    background-color: rgba(0, 0, 0, 0.5);");
document.writeln("  }");
document.writeln("  .back:hover {");
document.writeln("    background-color: rgba(0, 0, 0, 0.8);");
document.writeln("  }");
document.writeln("  </style>");
document.writeln("</head>");
document.writeln("<!--h1 style=\'color:blue;\'>这是一个蓝色的标题</h1-->");
document.writeln("<!--p style=\'color:red;\'>这是一段红色的文本</p-->");
document.writeln("<body>");
document.writeln("<div id=\'app\'>");
document.writeln("  <a class=\'back\' title=\'返回上级\' href=\'index.html\'></a>");
document.writeln("  <div class=\'title\'>海外宽带直连服务器地址列表</div>");
document.writeln("	<!--尺寸</font>-->");
document.writeln("	<table id=\'menuTable\'>");
document.writeln("	<tr style=\'display: table-rowspan; \'>");
document.writeln("	<tr>");
document.writeln("     <td><div style=\'text-align: center;\'><font size=5><p style=\'color:#ffe100;\'>&nbsp;&nbsp;&nbsp;&nbsp;省&nbsp;&nbsp;&nbsp;&nbsp;</p></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><font size=5><p style=\'color:#ffe100;\'>&nbsp;&nbsp;&nbsp;&nbsp;市&nbsp;&nbsp;&nbsp;&nbsp;</p></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><font size=5><p style=\'color:#ffe100;\'>服务器地址</p></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><font size=5><p style=\'color:#ffe100;\'>用户名1</p></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><font size=5><p style=\'color:#ffe100;\'>用户名2</p></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><font size=5><p style=\'color:#ffe100;\'>&nbsp;&nbsp;密&nbsp;&nbsp;码&nbsp;&nbsp;</p></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><font size=5><p style=\'color:#ffe100;\'>&nbsp;&nbsp;状&nbsp;&nbsp;态&nbsp;&nbsp;</p></font></div></td>");
document.writeln("    </tr>");
document.writeln("   <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>直辖市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>北京市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzbeijing.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>beijing1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("   </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>直辖市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>上海市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzshanghai.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>shanghai1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>直辖市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>天津市</h2></div></td>");
document.writeln("	 <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>haiwai.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#EC4C40;\'>暂未部署</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>直辖市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>重庆市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzchongqing.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>chongqing1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>广东省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>广州市</h2></div></td>");
document.writeln("	 <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzguangzhou.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>guangzhou1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>广东省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>深圳市</h2></div></td>");
document.writeln("	 <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzshenzhen.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>shenzhen1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽10M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>广东省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>中山市</h2></div></td>");
document.writeln("	 <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzzhongshan.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zhongshan1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽10M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>江苏省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>苏州市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzsuzhou.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>suzhou1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>江苏省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>镇江市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzzhenjiang.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zhenjiang1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽10M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>贵州省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>贵阳市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzguiyang.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>guiyang1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>四川省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>成都市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzchengdu.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>chengdu1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>四川省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>德阳市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzdeyang.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>deyang1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽10M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>陕西省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>西安市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzxian.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>xian1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>湖南省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>长沙市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzchangsha.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>changsha1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽20M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>湖北省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>武汉市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzwuhan.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wuhan1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽15M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>河南省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>新乡市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzxinxiang.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>xinxiang1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽10M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>浙江省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>杭州市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzhangzhou.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>hangzhou1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>/</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽15M</h2></div></td>");
document.writeln("     </tr>");
document.writeln("     <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>浙江省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>绍兴市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzhaoxing.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>shaoxing1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>/</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽15M</h2></div></td>");
document.writeln("     </tr>");
document.writeln("     <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>安徽省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>合肥市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzhefei.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>hefei1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽10M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>安徽省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>芜湖市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzwuhu.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wuhu1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽15M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>辽宁省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>大连市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzdalian.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>dalian1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽30M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>福建省</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#FF763E;\'>福州市</h2></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>zzfuzhou.wendy-ip.com</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>fuzhou1-10</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wdvpn</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\' class=\'content\'><font size=5><pre><p style=\'color:#3498db\'>wd123</p></pre></font></div></td>");
document.writeln("     <td><div style=\'text-align: center;\'><h2 style=\'color:#0ACD76;\'>正常，带宽10M</h2></div></td>");
document.writeln("    </tr>");
document.writeln("   </tbody>");
document.writeln("<script src=\'js/jquery.filtertable.min.js\'></script>");
document.writeln("<script src=\'js/filtertable.js\'></script>");
document.writeln("</table>");
document.writeln("</body>");
document.writeln("</html>");